version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: my_postgres_db
    restart: always
    environment:
      POSTGRES_USER: ad
      POSTGRES_PASSWORD: ad
      POSTGRES_DB: emtdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
